# Generated by Django 4.0.2 on 2022-02-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='phonenumber',
        ),
    ]
