# Generated by Django 4.0.2 on 2022-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udpated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('kakao_id', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=20)),
                ('point', models.IntegerField(default=100000)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
