# Generated by Django 4.0.2 on 2022-02-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrank_alter_user_kakao_id_alter_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.userrank'),
        ),
        migrations.AlterModelTable(
            name='userrank',
            table='users_ranks',
        ),
    ]
