# Generated by Django 4.0.2 on 2022-02-24 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductMedia',
            new_name='ProductCoverMedia',
        ),
        migrations.AlterField(
            model_name='community',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='community',
            name='parent_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AlterField(
            model_name='media',
            name='storage_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='productcovermedia',
            table='products_cover_media',
        ),
        migrations.CreateModel(
            name='ProductThumbnailMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.media')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'products_thumbnail_media',
            },
        ),
    ]
